### ISSUE TITLE
Bug en la interfaz

### ISSUE THREAD

**Issue by PPAGabriel** [NicolasRodriguezSteuerberg/Proyecto3ev#41]
En el momento de cargar la tabla Hospital, el label correspondiente al error de "Nro. de habitaciones", al ser String suele obviarlo y dice "Hospital modificado".

**Evaluar el código para asegurarnos que sea error de compilación y no de estructura.**

**Comment by NicolasRodriguezSteuerberg** [comment]
Tuvo que ser error de ejecución ya que ejecuté varias veces y me sacaba error cuando ponía alguna letra o signo. Por si acaso lo acabo de volver a intertar y me fue bien. Miraré la estructura para comprobar por si acaso

**Comment by NicolasRodriguezSteuerberg** [comment]
He comprobado el código y todo está bien. Fin
